baseURL: "https://acrazyczy.github.io"
title: Ziyi Cai
theme: PaperMod

enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    # - name: Books
    # url: books/
    # weight: 5
    - name: Publication
      url: publication/
      weight: 1
    - name: Talks
      url: talks/
      weight: 2
    - name: Teaching
      url: teaching/
      weight: 4
    - name: Projects
      url: projects/
      weight: 3
    # - name: Blog
    # url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
    # weight: 6

params:
  description: "This website hosts Ziyi Cai's publication, projects, curriculum vitae, and contact information."
  author: Ziyi Cai
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["publication", "teaching", "projects", "talks"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Ziyi Cai
    subtitle: "I am a third-year Ph.D. student in the [CS Theory Group](https://theory.cs.rutgers.edu/) at [Rutgers University](https://www.rutgers.edu/), advised by [Peng Zhang](https://sites.google.com/site/pengzhang27182/). My current interests are mainly in computational social choice and discrepancy theory."
    imageUrl: "avatar.jpg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Publication
        url: publication/
      - name: Talks
        url: talks/
      - name: Projects
        url: projects/
      - name: Teaching
        url: teaching/

      # - name: Courses
      # url: courses/
      # - name: Tags
      # url: tags/
      # - name: Archive
      # url: archive/
      # - name: Blog
      # url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: Email
      url: mailto:zc417@cs.rutgers.edu
    # - name: Zoom
    # url: https://www.zoom.us/my/igelfeld
    # - name: Location
    # url: location/
    # - name: Office Hours
    # url: officehours/
    - name: Google Scholar
      url: https://scholar.google.com/citations?AvA2C9UAAAAJ
    - name: GitHub
      url: https://github.com/acrazyczy
    # - name: Substack
    # url: https://pmichaillat.substack.com
    # - name: YouTube
    # url: https://www.youtube.com/@pmichaillat
    - name: Twitter
      url: https://x.com/crazycloud15
    # - name: Bluesky
    # url: https://bsky.app/profile/pmichaillat.bsky.social

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Ziyi Cai"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
